<?php

/**
 * This is the model base class for the table "{{gallery_images}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryImage".
 *
 * Columns in table "{{gallery_images}}" available as properties of the model,
 * followed by relations of table "{{gallery_images}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $gallery_id
 * @property string $name
 * @property string $image
 * @property string $description
 * @property string $create_time
 * @property string $update_time
 * @property integer $is_published
 * @property integer $priority
 *
 * @property Galleries $gallery
 */
abstract class BaseGalleryImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{gallery_images}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GalleryImage|GalleryImages', $n);
	}

	public static function representingColumn() {
		return 'gallery_id';
	}

	public function rules() {
		return array(
			array('name, gallery_id, image', 'required'),
			array('is_published, priority', 'numerical', 'integerOnly'=>true),
			array('gallery_id', 'length', 'max'=>16),
			array('name', 'length', 'max'=>64),
			array('image', 'length', 'max'=>255),
			array('description, create_time, update_time', 'safe'),
			array('gallery_id, name, image, description, create_time, update_time, is_published, priority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, gallery_id, name, image, description, create_time, update_time, is_published, priority', 'safe', 'on'=>'search'),
			array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
		);
	}

	public function relations() {
		return array(
			'gallery' => array(self::BELONGS_TO, 'Gallery', 'gallery_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}
	
	public function behaviors(){
		return array(
			'CTimestampBehavior' => array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'createAttribute' => 'create_time',
				'updateAttribute' => 'update_time',
			)
		);
	}
	
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'gallery_id' => null,
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'is_published' => Yii::t('app', 'Is Published'),
			'priority' => Yii::t('app', 'Priority'),
			'gallery' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('gallery_id', $this->gallery_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('is_published', $this->is_published);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}