<?php

/**
 * This is the model base class for the table "{{galleries}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gallery".
 *
 * Columns in table "{{galleries}}" available as properties of the model,
 * followed by relations of table "{{galleries}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $alias
 * @property string $image
 * @property string $description
 * @property string $content
 * @property integer $priority
 * @property string $create_time
 * @property string $update_time
 * @property integer $is_published
 *
 * @property GalleryImages[] $galleryImages
 */
abstract class BaseGallery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{galleries}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gallery|Galleries', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, alias', 'required'),
			array('priority, is_published', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>250),
			array('alias, image', 'length', 'max'=>255),
			array('description, content, create_time, update_time', 'safe'),
			array('image, description, content, create_time, update_time, is_published', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, alias, image, description, content, priority, create_time, update_time, is_published', 'safe', 'on'=>'search'),
			array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
		);
	}

	public function relations() {
		return array(
			'galleryImages' => array(self::HAS_MANY, 'GalleryImage', 'gallery_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}
	
	public function behaviors(){
		return array(
			'CTimestampBehavior' => array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'createAttribute' => 'create_time',
				'updateAttribute' => 'update_time',
			)
		);
	}
	
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'alias' => Yii::t('app', 'Alias'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'content' => Yii::t('app', 'Content'),
			'priority' => Yii::t('app', 'Priority'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'is_published' => Yii::t('app', 'Is Published'),
			'galleryImages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('priority', $this->priority);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('is_published', $this->is_published);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'defaultOrder'=>'priority ASC',
				'multiSort' =>true,
				'attributes' => array(
					'rating'=> array(
						'DESC' => 'create_time'
					)
				)
			),
		));
	}
}