<?php

/**
 * This is the model base class for the table "{{banners}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banner".
 *
 * Columns in table "{{banners}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $description
 * @property string $url
 * @property integer $priority
 * @property string $create_time
 * @property string $update_time
 *
 */
abstract class BaseBanner extends GxActiveRecord {
	public $image;
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{banners}}';
	}
	
	public static function label($n = 1) {
		return Yii::t('app', 'Banner|Banners', $n);
	}

	public static function representingColumn() {
		return 'title';
	}
	
	public function behaviors(){
		return array(
			'CTimestampBehavior' => array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'createAttribute' => 'create_time',
				'updateAttribute' => 'update_time',
			)
		);
	}
	
	public function rules() {
		return array(
			array('image', 'required'),
			//array('image', 'file', 'types'=>'jpg, gif, png'),
			array('title', 'length', 'max'=>255, 'on'=>'insert,update'),
			array('priority', 'numerical', 'integerOnly'=>true),
			array('title, image, description, url, create_time, update_time', 'safe'),
			array('title, image, description, url, priority, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, image, description, url, priority, create_time, update_time', 'safe', 'on'=>'search'),
			array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
			
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'url' => Yii::t('app', 'Url'),
			'priority' => Yii::t('app', 'Priority'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('priority', $this->priority);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'defaultOrder'=>'priority ASC',
				'multiSort' =>true,
				'attributes' => array(
					'rating'=> array(
						'DESC' => 'create_time'
					)
				)
			),
		));
	}
}