<?php

/**
 * This is the model base class for the table "{{news_middle}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsMiddle".
 *
 * Columns in table "{{news_middle}}" available as properties of the model,
 * followed by relations of table "{{news_middle}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $news_id
 *
 * @property NewsCategories $category
 * @property News $news
 */
abstract class BaseNewsMiddle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{news_middle}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsMiddle|NewsMiddles', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('category_id, news_id', 'required'),
			array('category_id, news_id', 'numerical', 'integerOnly'=>true),
			array('id, category_id, news_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'NewsCategories', 'category_id'),
			'news' => array(self::BELONGS_TO, 'News', 'news_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}
	
	
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'news_id' => null,
			'category' => null,
			'news' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('news_id', $this->news_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}