<?php

/**
 * This is the model base class for the table "{{news_categories}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsCategories".
 *
 * Columns in table "{{news_categories}}" available as properties of the model,
 * followed by relations of table "{{news_categories}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property integer $lft
 * @property integer $rght
 * @property integer $parent_id
 * @property string $image
 * @property string $description
 * @property string $content
 * @property integer $is_published
 * @property string $create_time
 * @property string $update_time
 *
 * @property NewsMiddle[] $newsMiddles
 */
abstract class BaseNewsCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{news_categories}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsCategories|NewsCategories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, alias', 'required'),
			array('lft, rght, parent_id, is_published', 'numerical', 'integerOnly'=>true),
			array('name, alias', 'length', 'max'=>64),
			array('image', 'length', 'max'=>255),
			array('description, content, create_time, update_time', 'safe'),
			array('lft, rght, parent_id, image, description, content, is_published, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, alias, lft, rght, parent_id, image, description, content, is_published, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'newsMiddles' => array(self::HAS_MANY, 'NewsMiddle', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}
	public function behaviors(){
		return array(
			'CTimestampBehavior' => array(
				'class' => 'zii.behaviors.CTimestampBehavior',
			)
		);
	}
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'alias' => Yii::t('app', 'Alias'),
			'lft' => Yii::t('app', 'Lft'),
			'rght' => Yii::t('app', 'Rght'),
			'parent_id' => Yii::t('app', 'Parent'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'content' => Yii::t('app', 'Content'),
			'is_published' => Yii::t('app', 'Is Published'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'newsMiddles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rght', $this->rght);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('is_published', $this->is_published);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}