<?php

/**
 * This is the model base class for the table "{{categories_demo}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CategoryDemo".
 *
 * Columns in table "{{categories_demo}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 *
 */
abstract class BaseCategoryDemo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{categories_demo}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CategoryDemo|CategoryDemos', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('lft, rgt, level', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('title, lft, rgt, level', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, lft, rgt, level', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rgt', $this->rgt);
		$criteria->compare('level', $this->level);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}