<?php

/**
 * This is the model base class for the table "categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "categories" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $image
 * @property string $created
 * @property string $modified
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property integer $root
 * @property integer $parent_id
 * @property string $description
 *
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_categories}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('lft, rgt, level, root, parent_id', 'numerical', 'integerOnly'=>true),
			array('name, alias, image, created, modified, description', 'safe'),
			array('name, alias, image, created, modified, lft, rgt, level, root, parent_id, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, alias, image, created, modified, lft, rgt, level, root, parent_id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'alias' => Yii::t('app', 'Alias'),
			'image' => Yii::t('app', 'Image'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'root' => Yii::t('app', 'Root'),
			'parent_id' => Yii::t('app', 'Parent'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rgt', $this->rgt);
		$criteria->compare('level', $this->level);
		$criteria->compare('root', $this->root);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}