<?php

/**
 * This is the model base class for the table "{{product_images}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductImage".
 *
 * Columns in table "{{product_images}}" available as properties of the model,
 * followed by relations of table "{{product_images}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $product_id
 * @property string $name
 * @property string $image
 * @property string $description
 * @property integer $priority
 * @property integer $is_published
 * @property string $create_time
 * @property string $update_time
 * @property string $color
 *
 * @property Products $product
 */
abstract class BaseProductImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_images}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductImage|ProductImages', $n);
	}

	public static function representingColumn() {
		return 'product_id';
	}

	public function behaviors(){
		return array(
			'CTimestampBehavior' => array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'createAttribute' => 'create_time',
				'updateAttribute' => 'update_time',
			)
		);
	}
	
	public function rules() {
		return array(
			array('priority, is_published', 'numerical', 'integerOnly'=>true),
			array('product_id', 'length', 'max'=>16),
			array('name', 'length', 'max'=>64),
			array('image', 'length', 'max'=>255),
			array('color', 'length', 'max'=>8),
			array('description, create_time, update_time', 'safe'),
			array('product_id, name, image, description, priority, is_published, create_time, update_time, color', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, name, image, description, priority, is_published, create_time, update_time, color', 'safe', 'on'=>'search'),
			array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'priority' => Yii::t('app', 'Priority'),
			'is_published' => Yii::t('app', 'Is Published'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'color' => Yii::t('app', 'Color'),
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('priority', $this->priority);
		$criteria->compare('is_published', $this->is_published);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('color', $this->color, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}