<?php

/**
 * This is the model base class for the table "{{product_categories}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductCategory".
 *
 * Columns in table "{{product_categories}}" available as properties of the model,
 * followed by relations of table "{{product_categories}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $image
 * @property string $description
 * @property integer $lft
 * @property integer $rght
 * @property integer $parent_id
 * @property integer $level
 * @property string $create_time
 * @property string $update_time
 *
 * @property ProductMiddle[] $productMiddles
 */
abstract class BaseProductCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_categories}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductCategory|ProductCategories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, alias', 'required'),
			array('lft, rght, parent_id, level', 'numerical', 'integerOnly'=>true),
			array('name, alias, image, description, create_time, update_time', 'safe'),
			array('name, alias, image, description, lft, rght, parent_id, level, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, alias, image, description, lft, rght, parent_id, level, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'productMiddles' => array(self::HAS_MANY, 'ProductMiddle', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'alias' => Yii::t('app', 'Alias'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'lft' => Yii::t('app', 'Lft'),
			'rght' => Yii::t('app', 'Rght'),
			'parent_id' => Yii::t('app', 'Parent'),
			'level' => Yii::t('app', 'Level'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'productMiddles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rght', $this->rght);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('level', $this->level);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}