<?php

/**
 * This is the model base class for the table "{{product_middle}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductMiddle".
 *
 * Columns in table "{{product_middle}}" available as properties of the model,
 * followed by relations of table "{{product_middle}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $product_id
 *
 * @property ProductCategories $category
 * @property Products $product
 */
abstract class BaseProductMiddle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_middle}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductMiddle|ProductMiddles', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('category_id, product_id', 'numerical', 'integerOnly'=>true),
			array('category_id, product_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, product_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'ProductCategories', 'category_id'),
			'product' => array(self::BELONGS_TO, 'Products', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'product_id' => null,
			'category' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('product_id', $this->product_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}